<a href="https://colab.research.google.com/github/evonyava/test/blob/main/%D0%9B%D0%A01_%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D1%94%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі

In [ ]:
import numpy as np
np.__version__


'2.0.2'

In [ ]:
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]

np.float64(5.0)

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[1, 1]

np.int64(5)

In [ ]:
a[0, 0]

np.int64(1)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
diag_a = np.diag(a)
diag_a

array([1, 5, 9])

In [ ]:
a_diag = np.diag(diag_a)
a_diag

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random.randint(11, size=(4,4))

array([[10,  5,  3,  7],
       [ 7,  0,  2,  0],
       [ 5, 10,  5,  1],
       [ 9,  4,  8, 10]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a_det = np.linalg.det(a)
a_det

np.float64(-2.0000000000000004)

In [ ]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
c = 3 * a
c

matrix([[ 3,  6,  9],
        [12, 15, 18]])

In [ ]:
a = np.matrix([[1, 6, 3], [8, 2, 7]])
b = np.matrix([[8, 1, 5], [6, 9, 12]])
c = a + b
c

matrix([[ 9,  7,  8],
        [14, 11, 19]])

In [ ]:
a = np.matrix([[1, 2], [4, 5]])
b = np.matrix([[7, 8], [9, 1]])
c = np.dot(a, b)
c

matrix([[25, 10],
        [73, 37]])

In [ ]:
np.multiply(a, b)

matrix([[ 7, 16],
        [36,  5]])

In [ ]:
a/b

matrix([[0.14285714, 0.25      ],
        [0.44444444, 5.        ]])

In [ ]:
np.divide(a, b)

matrix([[0.14285714, 0.25      ],
        [0.44444444, 5.        ]])

In [ ]:
a = np.matrix([[1, -3], [2, 5]])

a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.45454545,  0.27272727],
        [-0.18181818,  0.09090909]])

In [ ]:
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[0, -2, 2],
              [-4, 0, 2],
              [0, 2, 0]])

eigenvalues, eigenvectors = np.linalg.eig(a)

In [ ]:
print("Власні числа:")
eigenvalues


Власні числа:


array([-4.        ,  1.99999997,  2.00000003])

In [ ]:
print("\nВласні числа:")
eigenvectors


Власні числа:


array([[-5.57086015e-01,  1.11219577e-08, -1.11219579e-08],
       [-7.42781353e-01,  7.07106776e-01,  7.07106787e-01],
       [ 3.71390676e-01,  7.07106787e-01,  7.07106776e-01]])